name: Update Apps

on:
  push:
    paths:
      - 'apps/**'
      # Ignore changes from the action itself
      - '!apps/apps.md'
      - '!apps/data/nimiq-dist.json'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-apps:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: cd apps && pnpm install
        
      - name: Build apps
        run: cd apps && pnpm run build
        
      - name: Check for changes
        id: git-check
        run: |
          git add .
          git status --porcelain | grep -q "." && echo "changes=true" >> $GITHUB_OUTPUT || echo "changes=false" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: update apps documentation and dist files"
          git push
